version: '3.8'

services:
  mysql_8:
    container_name: mysql_8
    image: docker.io/bitnami/mysql:8.1
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MYSQL_ROOT_PASSWORD=pass
    # healthcheck:
    #   test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
    #   interval: 15s
    #   timeout: 5s
    #   retries: 6

volumes:
  mysql_data:
    driver: local