version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_stack_data:/data

volumes:
  redis_stack_data:
    driver: local